# Generated by Django 3.1 on 2020-08-28 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(blank=True, max_length=50)),
                ('placa', models.CharField(blank=True, max_length=50)),
                ('cor', models.CharField(blank=True, max_length=50)),
                ('ano', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50)),
                ('endereco', models.CharField(blank=True, max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('uf', models.CharField(choices=[['1', 'AC'], ['2', 'AL'], ['3', 'AP'], ['4', 'AM'], ['5', 'BA'], ['6', 'CE'], ['7', 'DF'], ['8', 'ES'], ['9', 'GO'], ['10', 'MA'], ['11', 'MT'], ['12', 'MS'], ['13', 'MG'], ['14', 'PA'], ['15', 'PB'], ['16', 'PR'], ['17', 'PE'], ['18', 'PI'], ['19', 'RJ'], ['20', 'RN'], ['21', 'RS'], ['22', 'RO'], ['23', 'RR'], ['24', 'SC'], ['25', 'SP'], ['26', 'SE'], ['27', 'TO']], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaga', models.CharField(blank=True, max_length=10)),
                ('cliente', models.CharField(blank=True, max_length=120)),
                ('carro', models.CharField(blank=True, max_length=80)),
                ('inicio', models.CharField(blank=True, max_length=10)),
                ('fim', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(choices=[['T', 'Livre'], ['F', 'Ocupado']], max_length=1)),
            ],
        ),
    ]
