# Generated by Django 3.1 on 2020-08-20 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_auto_20200819_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='ano',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='carro',
            name='cor',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='carro',
            name='modelo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='carro',
            name='placa',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fim',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='inicio',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='vaga',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
