# Generated by Django 3.1 on 2020-08-20 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_auto_20200819_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[['T', 'Livre'], ['F', 'Ocupado']], max_length=1),
        ),
    ]
