# Generated by Django 3.1 on 2020-08-20 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_auto_20200819_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='uf',
            field=models.CharField(choices=[['1', 'AC'], ['2', 'AL'], ['3', 'AP'], ['4', 'AM'], ['5', 'BA'], ['6', 'CE'], ['7', 'DF'], ['8', 'ES'], ['9', 'GO'], ['10', 'MA'], ['11', 'MT'], ['12', 'MS'], ['13', 'MG'], ['14', 'PA'], ['15', 'PB'], ['16', 'PR'], ['17', 'PE'], ['18', 'PI'], ['19', 'RJ'], ['20', 'RN'], ['21', 'RS'], ['22', 'RO'], ['23', 'RR'], ['24', 'SC'], ['25', 'SP'], ['26', 'SE'], ['27', 'TO']], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
